language: go
sudo: false
go:
  - 1.15.x
  - 1.14.x
  - 1.13.x
script:
  - go get -u golang.org/x/lint/golint
  - OUT="$(go get -a)"; test -z "$OUT" || (echo "$OUT" && return 1)
  - OUT="$(gofmt -l -d ./)"; test -z "$OUT" || (echo "$OUT" && return 1)
  - go vet -v ./...
  - go test github.com/MaximeWeyl/goTestifyRecursive -v  -coverprofile=coverage.txt -covermode=atomic -coverpkg ./*
  - go build
after_success:
  - bash <(curl -s https://codecov.io/bash)
